def cues(row: int, count: int):
    return [f"/cues/selected/cues/by_cell/col_{i + 1}/row_{row}" for i in range(count)]


MADMAPPER_ADDRESSES = {
    "fg2": {
        "cues": {
            "birds": cues(4, 4),
            "falling_trees": cues(19, 1),
            "fires": cues(24, 8),
            "flowers": cues(29, 4),
            "forest": cues(34, 1),
            "mushrooms": cues(42, 5),
            "rain": cues(47, 2),
            "storms": cues(61, 3),
            "winter": cues(69, 1),
        },
        "feedback_amount": "/surfaces/Layers/Background_2_Layers/Background_2_Layer_Feedback/opacity",
        "feedback_fx_amount": [],
        "fx_amount": [],
        "mask_opacity": "/surfaces/Layers/Foreground_2_Layers/Foreground_2_Layer_Mask/opacity",
        "opacity": "/surfaces/Main/Foreground_2/opacity",
    },
    "fg1": {
        "cues": {
            "birds": cues(5, 2),
            "falling_tree": cues(20, 1),
            "fires": cues(25, 2),
            "flowers": cues(30, 3),
            "forest": cues(35, 1),
            "mushrooms": cues(43, 5),
            "storms": cues(62, 3),
        },
        "feedback_amount": "/surfaces/Layers/Foreground_1_Layers/Foreground_1_Layer_Feedback/opacity",
        "feedback_fx_amount": [],
        "fx_amount": [],
        "mask_opacity": "/surfaces/Layers/Foreground_1_Layers/Foreground_1_Layer_Mask/opacity",
        "opacity": "/surfaces/Main/Foreground_1/opacity",
    },
    "bg2" : {
        "cues": {
            "boreal": cues(1, 3),
            "deaad": cues(7, 2),
            "deforestation": cues(10, 2),
            "dry_pine": cues(13, 4),
            "fall": cues(16, 5),
            "falling_trees": cues(21, 1),
            "fires": cues(26, 9),
            "flowers": cues(31, 6),
            "forest": cues(36, 3),
            "mountains": cues(39, 3),
            "mushrooms": cues(44, 2),
            "rain": cues(49, 6),
            "rainforest": cues(52, 8),
            "smoke": cues(55, 5),
            "spring": cues(58, 5),
            "storms": cues(63, 3),
            "summer": cues(66, 6),
            "winter": cues(71, 5),
        },
        "feedback_amount": "/surfaces/Layers/Background_2_Layers/Background_2_Layer_Feedback/opacity",
        "feedback_fx_amount": [],
        "fx_amount": [],
        "mask_opacity": "/surfaces/Layers/Background_2_Layers/Background_2_Layer_Mask/opacity",
        "opacity": "/surfaces/Main/Background_2/opacity",
    },
    "bg1": {
        "cues": {
            "boreal": cues(2, 2),
            "dead": cues(8, 5),
            "deforestation": cues(11, 2),
            "dry_pine": cues(14, 4),
            "fall": cues(17, 5),
            "falling_trees": cues(22, 1), 
            "fires": cues(27, 7),
            "flowers": cues(32, 6),
            "forest": cues(37, 6),
            "mountains": cues(40, 2),
            "mushrooms": cues(45, 2),
            "rain": cues(50, 6),
            "rainforest": cues(53, 8),
            "smoke": cues(56, 5),
            "spring": cues(59, 4),
            "storms": cues(64, 2),
            "summer": cues(67, 6),
            "winter": cues(72, 6),
        },
        "feedback_amount": "/surfaces/Layers/Background_1_Layers/Background_1_Layer_Feedback/opacity",
        "feedback_fx_amount": [],
        "fx_amount": [],
        "mask_opacity": "/surfaces/Layers/Background_1_Layers/Background_1_Layer_Mask/opacity",
        "opacity": "/surfaces/Main/Background_1/opacity",
    },
}